name: Node CI

on:
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:
  build:

    runs-on: self-hosted



    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '17.4.0'
        cache: 'npm'
    - run: npm install
    - run: npm start
